- name: Deploy Kubernetes resources
  hosts: localhost
  tasks:
    - name: Create namespaces
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ item }}"
      loop:
        - webgoat
        - monitoring

    - name: Deploy WebGoat application
      k8s:
        state: present
        namespace: webgoat
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: webgoat
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: webgoat
            template:
              metadata:
                labels:
                  app: webgoat
              spec:
                containers:
                  - name: webgoat
                    image: webgoat/webgoat:latest
                    ports:
                      - containerPort: 8080

    - name: Deploy PostgreSQL
      k8s:
        state: present
        namespace: webgoat
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: postgres
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: postgres
            template:
              metadata:
                labels:
                  app: postgres
              spec:
                containers:
                  - name: postgres
                    image: postgres:latest
                    env:
                      - name: POSTGRES_USER
                        value: admin
                      - name: POSTGRES_PASSWORD
                        value: password
                    ports:
                      - containerPort: 5432

    - name: Deploy Prometheus
      k8s:
        state: present
        namespace: monitoring
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: prometheus
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: prometheus
            template:
              metadata:
                labels:
                  app: prometheus
              spec:
                containers:
                  - name: prometheus
                    image: prom/prometheus:latest
                    ports:
                      - containerPort: 9090

    - name: Deploy Grafana
      k8s:
        state: present
        namespace: monitoring
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: grafana
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: grafana
            template:
              metadata:
                labels:
                  app: grafana
              spec:
                containers:
                  - name: grafana
                    image: grafana/grafana:latest
                    ports:
                      - containerPort: 3000

    - name: Deploy Alertmanager
      k8s:
        state: present
        namespace: monitoring
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: alertmanager
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: alertmanager
            template:
              metadata:
                labels:
                  app: alertmanager
              spec:
                containers:
                  - name: alertmanager
                    image: prom/alertmanager:latest
                    ports:
                      - containerPort: 9093
