- name: Deploy WebGoat to AKS
  hosts: localhost
  tasks:
    #- name: Set kubeconfig
    #  shell: az aks get-credentials --resource-group aks-resource-group --name webgoat-aks-cluster
    

    - name: Create namespace
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/namespace.yml') }}"
    
    - name: Install NGINX Ingress Controller
      command: >
        kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml
      register: ingress_result
    - debug: var=ingress_result

    - name: Wait for Ingress Controller to be ready
      command: kubectl wait --namespace ingress-nginx --for=condition=ready pod -l app.kubernetes.io/component=controller --timeout=120s

    - name: Generate a self-signed certificate
      command: >
        openssl req -x509 -nodes -days 365 -newkey rsa:2048
        -keyout /tmp/webgoat.key -out /tmp/webgoat.crt
        -subj "/CN=webgoat.local"

    - name: Create Kubernetes secret for TLS
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: webgoat-tls
            namespace: webgoat-namespace
          type: kubernetes.io/tls
          data:
            tls.crt: "{{ lookup('file', '/tmp/webgoat.crt') | b64encode }}"
            tls.key: "{{ lookup('file', '/tmp/webgoat.key') | b64encode }}"


    - name: Install Cert-Manager
      command: >
        kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.0/cert-manager.yaml
   
    - name: Apply ClusterIssuer
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/cluster-issuer.yml') }}"
    
    - name: Apply Certificate
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/certificate.yml') }}"

    - name: Apply RBAC configuration
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/rbac.yml') }}"

    - name: Apply deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/deployment.yml') }}"
        
    - name: Apply service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/service.yml') }}"

    # Configuration de l'Ingress avec HTTPS
    - name: Apply Ingress for WebGoat with HTTPS
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: webgoat-ingress
            namespace: webgoat-namespace
            annotations:
              kubernetes.io/ingress.class: "nginx"
          spec:
            tls:
            - hosts:
              - webgoat.local
              secretName: webgoat-tls
            rules:
            - host: webgoat.local
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: webgoat-service
                      port:
                        number: 8080
