apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webgoat-cert
  namespace: webgoat-namespace
spec:
  secretName: webgoat-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - webgoat.example.com