apiVersion: apps/v1
kind: Deployment
metadata:
    name: webgoat-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: webgoat
    template:
        metadata:
            labels:
                app: webgoat
        spec:
            containers:
                - name: webgoat
                  image: webgoat/webgoat:latest
                  resources:
                    requests:
                        memory: "512Mi"
                        cpu: "250m"
                    limits:
                        memory: "1Gi"
                        cpu: "500m"
                  ports:
                      - containerPort: 8080
