apiVersion: apps/v1
kind: Deployment
metadata:
    name: webgoat-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: webgoat
    template:
        metadata:
            labels:
                app: webgoat
        spec:
            containers:
                - name: webgoat
                  image: webgoat/webgoat:latest
                  ports:
                      - containerPort: 8080
