apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webgoat-ingress
  namespace: webgoat-namespace
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - "*"
    secretName: webgoat-tls
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webgoat-service
            port:
              number: 8080