apiVersion: v1
kind: Service
metadata:
    name: webgoat-service
spec:
    selector:
        app: webgoat
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
    type: LoadBalancer
