apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: 'discord-webhook'
    receivers:
    - name: 'discord-webhook'
      webhook_configs:
      - url: "$(WEBHOOK_URL)"
