apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat-deployment
  namespace: webgoat
  labels:
    app: webgoat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webgoat
  template:
    metadata:
      labels:
        app: webgoat
    spec:
      containers:
        - name: webgoat
          image: aurelter/log8100_tp3:latest
          ports:
          - containerPort: 8080
          resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
