- name: Create monitoring namespace
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ monitoring.namespace }}"
    kubeconfig: "{{ kubeconfig_path }}"

- name: Deploy Prometheus
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', '../templates/prometheus_deployment.yml') }}"
    kubeconfig: "{{ kubeconfig_path }}"

- name: Deploy Grafana
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', '../templates/grafana_deployment.yml') }}"
    kubeconfig: "{{ kubeconfig_path }}"

- name: Deploy AlertManager
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', '../templates/alertmanager_deployment.yml') }}"
    kubeconfig: "{{ kubeconfig_path }}"