name: Deploy to AKS using Ansible

on:
    workflow_dispatch:
    workflow_call:
    push:
      branches:
        - features/terraform-k8s

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Python environment for Ansible
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Ansible and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible kubernetes

    # 3. Decode and set up kubeconfig
    - name: Set up kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > ./kubeconfig
        export KUBECONFIG=./kubeconfig
        kubectl get nodes

    # 4. Deploy with Ansible
    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i localhost, terraform/deploy.yml
