name: Docker Scout

on:
  workflow_dispatch:
  workflow_call:

jobs:
  docker_scout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
  
      - name: Download image
        uses: ishworkh/container-image-artifact-download@v2.0.0
        with:
          image: "${{ secrets.DOCKER_USERNAME }}/log8100_tp3:latest"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations
          ignore-unchanged: true
          only-fixed: true
          exit-code: 1
          #exit-on: vulnerability, policy

      - name: Send Discord alert
        if: failure() 
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
               -d '{"content": "❌ Le workflow GitHub a échoué sur la branche **${{ github.ref_name }}** au job **${{ github.job }}**. Consultez les logs : ${{ github.run_url }}"}' \
               $WEBHOOK_URL
