name: Pipeline

on:
  push:
    branches:
      - main
      - feature/pipline
  workflow_dispatch:

jobs:
    call_trivy:
        uses: ./.github/workflows/trivy.yml
        secrets: inherit
        
    call_docker_scout:
      uses: ./.github/workflows/docker_scout.yml
      secrets: inherit

    call_discord_alert:
      uses: ./.github/workflows/discord-alert.yml
      secrets: inherit

    call_docker_publish:
      uses: ./.github/workflows/docker_publish.yml
      secrets: inherit
      needs:
        - call_trivy
        - call_docker_scout
        - call_discord_alert
