name: Pipeline CD

on:
  workflow_call:
  workflow_dispatch:

jobs:

    call_docker-publish:
      uses: ./.github/workflows/docker-publish.yml
      secrets: inherit

    call_terraform:
      uses: ./.github/workflows/terraform.yml
      secrets: inherit

    call_ansible:
      uses: ./.github/workflows/ansible.yml
      secrets: inherit
      needs: call_terraform
