name: Pipeline

on:
  # push:
  #   branches:
  #     - main
  #     - feature/pipline
  workflow_dispatch:

jobs:

    build_image:
      uses: ./.github/workflows/build_img.yml
      secrets: inherit

    call_trivy:
      needs: build_image  
      uses: ./.github/workflows/trivy.yml
        
    call_docker_scout:
      needs: build_image
      uses: ./.github/workflows/docker_scout.yml
      secrets: inherit

    call_discort-alert:
      uses: ./.github/workflows/discort-alert.yml
      secrets: inherit

    call_snyk:
      uses: ./.github/workflows/snyk.yml
      secrets: inherit

    call_zap:
      needs: build_image
      uses: ./.github/workflows/zap.yml
