name: launch trivy

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'webgoat/webgoat_image'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
        env:
          TRIVY_DB_REPOSITORY: 'aquasec/trivy-db:2'
          TRIVY_JAVA_DB_REPOSITORY: 'aquasec/trivy-java-db:1'
          TRIVY_TIMEOUT: '20m'
